// Module J - Agentic Career Workflow Engine.
//
// The allowed-action registry the planner is restricted to (Phase 2's "the planner
// should NOT execute arbitrary actions" requirement). Every action name here must have
// exactly one corresponding entry in toolRegistry.js - the executor throws if a plan
// ever references an action this file doesn't list.

const CAREER_GOALS = {
  FIND_JOBS: "FIND_JOBS",
  PRIORITIZE_JOBS: "PRIORITIZE_JOBS",
  ANALYZE_SKILL_GAPS: "ANALYZE_SKILL_GAPS",
  ANALYZE_APPLICATIONS: "ANALYZE_APPLICATIONS",
  CAREER_PLANNING: "CAREER_PLANNING",
  RESUME_IMPROVEMENT: "RESUME_IMPROVEMENT",
  INTERVIEW_PREPARATION: "INTERVIEW_PREPARATION",
  WEEKLY_CAREER_PLAN: "WEEKLY_CAREER_PLAN",
  JOB_SEARCH_STRATEGY: "JOB_SEARCH_STRATEGY",
  UNKNOWN: "UNKNOWN",
};

const CAREER_ACTIONS = {
  GET_CANDIDATE_PROFILE: "GET_CANDIDATE_PROFILE",
  SEARCH_JOBS: "SEARCH_JOBS",
  CALCULATE_MATCH: "CALCULATE_MATCH",
  ANALYZE_SKILLS: "ANALYZE_SKILLS",
  ANALYZE_APPLICATIONS: "ANALYZE_APPLICATIONS",
  GET_CAREER_INSIGHTS: "GET_CAREER_INSIGHTS",
  PREPARE_INTERVIEW: "PREPARE_INTERVIEW",
};

// Goal -> ordered list of actions. Fixed, reviewable data - not something an LLM
// decides at runtime, per Phase 2's determinism requirement. CAREER_PLANNING and
// JOB_SEARCH_STRATEGY intentionally share a plan (Workflow D): both goals converge on
// the same "combine everything into a strategy" flow, they just start from different
// phrasing of the same underlying request.
const EXECUTION_PLANS = {
  [CAREER_GOALS.FIND_JOBS]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.SEARCH_JOBS,
    CAREER_ACTIONS.ANALYZE_SKILLS,
  ],
  [CAREER_GOALS.PRIORITIZE_JOBS]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.SEARCH_JOBS,
  ],
  [CAREER_GOALS.ANALYZE_SKILL_GAPS]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.SEARCH_JOBS,
    CAREER_ACTIONS.ANALYZE_SKILLS,
  ],
  [CAREER_GOALS.ANALYZE_APPLICATIONS]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.ANALYZE_APPLICATIONS,
  ],
  [CAREER_GOALS.CAREER_PLANNING]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.SEARCH_JOBS,
    CAREER_ACTIONS.ANALYZE_SKILLS,
    CAREER_ACTIONS.ANALYZE_APPLICATIONS,
    CAREER_ACTIONS.GET_CAREER_INSIGHTS,
  ],
  [CAREER_GOALS.JOB_SEARCH_STRATEGY]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.SEARCH_JOBS,
    CAREER_ACTIONS.ANALYZE_SKILLS,
    CAREER_ACTIONS.ANALYZE_APPLICATIONS,
    CAREER_ACTIONS.GET_CAREER_INSIGHTS,
  ],
  [CAREER_GOALS.WEEKLY_CAREER_PLAN]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.ANALYZE_APPLICATIONS,
    CAREER_ACTIONS.SEARCH_JOBS,
    CAREER_ACTIONS.GET_CAREER_INSIGHTS,
  ],
  [CAREER_GOALS.RESUME_IMPROVEMENT]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.SEARCH_JOBS,
    CAREER_ACTIONS.ANALYZE_SKILLS,
    CAREER_ACTIONS.GET_CAREER_INSIGHTS,
  ],
  [CAREER_GOALS.INTERVIEW_PREPARATION]: [
    CAREER_ACTIONS.GET_CANDIDATE_PROFILE,
    CAREER_ACTIONS.SEARCH_JOBS,
    CAREER_ACTIONS.ANALYZE_SKILLS,
    CAREER_ACTIONS.PREPARE_INTERVIEW,
  ],
  [CAREER_GOALS.UNKNOWN]: [],
};

export { CAREER_GOALS, CAREER_ACTIONS, EXECUTION_PLANS };
